### ISSUE TITLE
Add `isEqual` function

### ISSUE THREAD

**Issue by mlhaufe** [abozhilov/set-utils#1]
An `isEqual` function is missing.

Definition:
Two sets are equal if and only if they have the same elements..

The Set {2,4,6} is equal to {6,2,4}
The Set {2,4,6} is equal to {2,2,2,2,4,4,6,6,6,6,6,6}

**Comment by mlhaufe** [comment]
Semantically equivalent to the following:

```ts
function isEqual<Т>(setA:Set<Т>, setB:Set<Т>): boolean { 
    return isSubset(setA, setB) && isSubset(setB, setA)
}
```

**Comment by abozhilov** [comment]
Nice idea. I'll add this function.
