### ISSUE TITLE
Add `powerSet` function

### ISSUE THREAD

**Issue by mlhaufe** [abozhilov/set-utils#2]
The power set of `{0, 1, 2}` is the set of all subsets of `{0, 1, 2}` including the empty set &empty; and the set itself:

```js
powerSet(new Set([0, 1, 2]))
```

produces:

```js
new Set([
    new Set([]),
    new Set([0]),
    new Set([1]),
    new Set([2]),
    new Set([0, 1]),
    new Set([0, 2]),
    new Set([1, 2]),
    new Set([0, 1, 2])
])
```

**Comment by abozhilov** [comment]
Thanks. Due to time complexity required for all subsets generation I'd rather implement it as a generator and I'll delegate to the user how many sets to be generated.
