### ISSUE TITLE
Add `cross` function

### ISSUE THREAD

**Issue by mlhaufe** [abozhilov/set-utils#3]
Add a `cross` function to provide the ability to create Cartesian Products (`A x B`)

```
A = {1, 2}
B = {a, b, c}

A x B = { (1, a), (1, b), (1, c), (2, a), (2, b), (2, c) }
```

```js
const A = new Set([1, 2]),
      B = new Set(['a', 'b', 'c'])

cross(A, B)
```

Produces:

```js
new Set([
    [1, 'a'],
    [1, 'b'],
    [1, 'c'],
    [2, 'a'],
    [2, 'b'],
    [2, 'c']
])
```

**Comment by abozhilov** [comment]
I think this method is bettet to be generalized and it might work with any iterable. 
See: https://github.com/abozhilov/ES-Iter/blob/master/src/Iter.js#L449
